#!/bin/bash

# WEEK 1 QUICK START GUIDE
# Run these commands to test the Brain system

echo "====== WEEK 1 QUICK START ======"
echo ""
echo "1. Verify components:"
echo "   uv run python verify_week_1.py"
echo ""
echo "2. Run unit tests:"
echo "   uv run pytest tests/test_week_1_brain.py -v"
echo ""
echo "3. Start Ollama (in another terminal):"
echo "   ollama serve"
echo ""
echo "4. Use in Python code:"
echo "   from providers.brain import Brain"
echo "   from providers.local.ollama_engine import OllamaEngine"
echo "   ollama = OllamaEngine(model_name='mistral')"
echo "   brain = Brain(ollama)"
echo "   result = await brain.think('your question')"
echo ""
echo "====== API SUMMARY ======="
echo ""
echo "Brain API:"
echo "  - brain.think(input_str) -> str (synchronous)"
echo "  - brain.stream_think(input_str) -> AsyncIterator[str] (streaming)"
echo "  - brain.get_last_reasoning() -> dict"
echo "  - brain.explain_last_decision() -> str"
echo ""
echo "IntentDetector API:"
echo "  - detector.detect(input_str) -> IntentResult"
echo "  - detector.get_keywords(input_str) -> List[str]"
echo ""
echo "ModelSelector API:"
echo "  - selector.select(intent_result) -> ModelSelectionResult"
echo "  - selector.set_model_availability(model, available)"
echo ""
